[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.volumes]]
mountPath = "/app/prisma"
name = "sqlite-data"
